### ISSUE TITLE
Protocol error (Fetch.getResponseBody): Can only get response body on requests captured after headers received.

### ISSUE THREAD

**Issue by Ren232** [niieani/puppeteer-intercept-and-modify-requests#9]
On websites that take longer to load the following error can occur. I managed to patch it up by adding try-catches but it isn't a long term fix.

                error: new Errors_js_1.ProtocolError(),
                       ^

ProtocolError: Protocol error (Fetch.getResponseBody): Can only get response body on requests captured after headers received.
    at C:\Users\renes\Documents\projects\F1LiveFinder\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:329:24
    at new Promise (<anonymous>)
    at CDPSessionImpl.send (C:\Users\renes\Documents\projects\F1LiveFinder\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:325:16)
    at RequestInterceptionManager.onRequestPausedEvent (C:\Users\renes\Documents\projects\F1LiveFinder\node_modules\puppeteer-intercept-and-modify-requests\cjs\main.js:65:114)

**Comment by niieani** [comment]
Is there a way I can reproduce this issue?

**Comment by Ren232** [comment]
Thanks for the fast reaction. I got the error by going to a website that has slow response times. 
I was able to reproduce the error again on "https://www.theworldsworstwebsiteever.com/" by refreshing.
